#!/usr/bin/env python3

#*********************************************************************************
#                                                                                *
# This file is part of the "luna-samples" project.                               *
#                                                                                *
# The "luna-samples" project is provided under the MIT license (see the          *
# following Web site for further details: https://mit-license.org/ ).            *
#                                                                                *
# Copyright © 2025 Thales Group                                                  *
#                                                                                *
#*********************************************************************************


# OBJECTIVE :
# - This code demonstrates how to delete a user account from a Luna Network HSM.




import sys
import os
import requests
import base64
import urllib3
import getpass
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)



# Prints the correct syntax to execute this code.
if len(sys.argv) != 3:
	print ("\nusage :-")
	print ("./user_delete <HSM_IP_OR_HOST> <appliance_username>\n")
	quit()
else:
	hostname = sys.argv[1]
	username = sys.argv[2]
	password = getpass.getpass(prompt="["+ username + "] Password : ")
	auth = username + ":" + password

authString = base64.b64encode(bytes(auth, 'utf-8')).decode("ascii")
header = {'Content-type': 'application/vnd.safenetinc.lunasa+json;version=', 'Authorization': 'Basic %s' % authString}
response = 0



# Ask for the username to delete and confirmation before deleting it.
try:
	user_name = input("\nUSER-ID : ")
	confirmation = input("Are you sure you want to delete this user? Type 'delete-this-user' to confirm : ")
	if (confirmation=='delete-this-user'):
		url = "https://"+hostname+":8443/users/"+user_name
		response = requests.delete(url, headers=header, verify=False)
	else:
		print ("\nNo changes were made, exiting now...")
		quit()

except OSError as osErr:
	print("\tFailed to connect to :"+hostname)
	print("\tReason: ", osErr)
	quit()

if response.status_code==401:
	print("Login failed.")
	quit()

if response.status_code!=204:
	print("Response code :",response.status_code)
	quit()
else:
	print ("\nUsername:", user_name, "deleted successfully.")

print ()
