#!/usr/bin/env python3

#*********************************************************************************
#                                                                                *
# This file is part of the "luna-samples" project.                               *
#                                                                                *
# The "luna-samples" project is provided under the MIT license (see the          *
# following Web site for further details: https://mit-license.org/ ).            *
#                                                                                *
# Copyright © 2025 Thales Group                                                  *
#                                                                                *
#*********************************************************************************


# OBJECTIVE :
# - This code demonstrates how to create a new user using Luna REST API.
# - A temporary password is assigned to the user upon creation.
# - The user must change this password during their first login.

import sys
import os
import random
import requests
import base64
import urllib3
import getpass
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890/@#$?*-_+="




if len(sys.argv) != 3:
	print ("\nusage :-")
	print ("./user_create <HSM_IP_OR_HOST> <appliance_username>\n")
	quit()
else:
	hostname = sys.argv[1]
	username = sys.argv[2]
	password = getpass.getpass(prompt="["+ username + "] Password : ")
	auth = username + ":" + password

authString = base64.b64encode(bytes(auth, 'utf-8')).decode("ascii")
url = "https://"+hostname+":8443/users"
header = {'Content-type': 'application/vnd.safenetinc.lunasa+json;version=', 'Authorization': 'Basic %s' % authString}
response = 0




print ("Connecting to Luna HSM : [",hostname,"]\n")
try:
	user_name = input("Username : ")
	full_name = input("Fullname : ")
	email_address = input("Email Address : ")
	role = input("Role : ")
	user_password = ""
	for ctr in range(16):
		user_password+=random.choice(characters)

	data = '{"userId": "' + user_name + '", "fullName": "' + full_name + '", "email": "' + email_address + '", "role": "' + role + '", "password": "' + user_password + '"}'
	response = requests.post(url, data, headers=header, verify=False)
except OSError as osErr:
	print("\tFailed to connect to :"+hostname)
	print("\tReason: ", osErr)
	quit()

if response.status_code==401:
	print("Login failed.")
	quit()

if response.status_code!=204:
	print("User creation failed. Response code :",response.status_code)
	quit()
else:
	print ("\nUsername '", user_name, "'created successfully.")
	print ("TEMPORARY PASSWORD : ", user_password)

print ()
